### ISSUE TITLE
Windows reporting battery status unknown when charger plugged in

### ISSUE THREAD

**Issue by AlexCrane** [distatus/battery#7]
Did a bit of digging on this, and seems BATTERY_STATUS::Powerstate is set to 0x5 

This is BATTERY_POWER_ON_LINE | BATTERY_CHARGING , and I think should be treated like State.Charging

I'll put in an MR to fix shortly

**Comment by KenjiTakahashi** [comment]
Ah, thanks for the report. Now I wonder what other combinations of these flags are possible?

Feel free to send a PR. Otherwise, I'll try to look into it over the weekend.

**Comment by KenjiTakahashi** [comment]
Should be fixed now.
